sudo: false
language: java
jdk:
- oraclejdk8
before_script:
- git config --global user.email "monaka@monami-ya.jp"
- git config --global user.name "Masaki Muranaka"
script: mvn install
deploy:
  skip_cleanup: true
  provider: script
  script: "deploy.sh"
  on:
    branch: pr-fix-deployment-error
env:
  global:
  - MAVEN_OPTS="-Xmx2048m -XX:MaxPermSize=128m"
  - secure: IfCx+0G+TwkCtsqlXk75XgcZhyF/HgGRcuQ0PaOin3YMTomm9qO43aO9zmeQXhT+A5zo15cQsO2CoSqZHJmV/V8AnQqaWX0oJNrjxZUuKSUJyPWbxW7PHbKs95+3yF3vKcj49TwIMkP/egDRVPeExRnWdBEL8rFK92MDJdE4zAE=
