/**
 */
package jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.provider;

import java.util.ArrayList;
import java.util.Collection;

import jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.util.InteractionAdapterFactory;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class InteractionItemProviderAdapterFactory extends InteractionAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public InteractionItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.InteractionObject} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InteractionObjectItemProvider interactionObjectItemProvider;

	/**
	 * This creates an adapter for a {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.InteractionObject}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInteractionObjectAdapter() {
		if (interactionObjectItemProvider == null) {
			interactionObjectItemProvider = new InteractionObjectItemProvider(this);
		}

		return interactionObjectItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.InteractionReferrable} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InteractionReferrableItemProvider interactionReferrableItemProvider;

	/**
	 * This creates an adapter for a {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.InteractionReferrable}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInteractionReferrableAdapter() {
		if (interactionReferrableItemProvider == null) {
			interactionReferrableItemProvider = new InteractionReferrableItemProvider(this);
		}

		return interactionReferrableItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.InternalEcuSender} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InternalEcuSenderItemProvider internalEcuSenderItemProvider;

	/**
	 * This creates an adapter for a {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.InternalEcuSender}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInternalEcuSenderAdapter() {
		if (internalEcuSenderItemProvider == null) {
			internalEcuSenderItemProvider = new InternalEcuSenderItemProvider(this);
		}

		return internalEcuSenderItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.ExternalEcuSender} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExternalEcuSenderItemProvider externalEcuSenderItemProvider;

	/**
	 * This creates an adapter for a {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.ExternalEcuSender}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExternalEcuSenderAdapter() {
		if (externalEcuSenderItemProvider == null) {
			externalEcuSenderItemProvider = new ExternalEcuSenderItemProvider(this);
		}

		return externalEcuSenderItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.SendInteraction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SendInteractionItemProvider sendInteractionItemProvider;

	/**
	 * This creates an adapter for a {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.SendInteraction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSendInteractionAdapter() {
		if (sendInteractionItemProvider == null) {
			sendInteractionItemProvider = new SendInteractionItemProvider(this);
		}

		return sendInteractionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.ReceiveInteraction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReceiveInteractionItemProvider receiveInteractionItemProvider;

	/**
	 * This creates an adapter for a {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.ReceiveInteraction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReceiveInteractionAdapter() {
		if (receiveInteractionItemProvider == null) {
			receiveInteractionItemProvider = new ReceiveInteractionItemProvider(this);
		}

		return receiveInteractionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.Receiver} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReceiverItemProvider receiverItemProvider;

	/**
	 * This creates an adapter for a {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.Receiver}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReceiverAdapter() {
		if (receiverItemProvider == null) {
			receiverItemProvider = new ReceiverItemProvider(this);
		}

		return receiverItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.InternalEcuReceiver} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InternalEcuReceiverItemProvider internalEcuReceiverItemProvider;

	/**
	 * This creates an adapter for a {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.InternalEcuReceiver}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInternalEcuReceiverAdapter() {
		if (internalEcuReceiverItemProvider == null) {
			internalEcuReceiverItemProvider = new InternalEcuReceiverItemProvider(this);
		}

		return internalEcuReceiverItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.RteValueBufferImplementation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RteValueBufferImplementationItemProvider rteValueBufferImplementationItemProvider;

	/**
	 * This creates an adapter for a {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.RteValueBufferImplementation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRteValueBufferImplementationAdapter() {
		if (rteValueBufferImplementationItemProvider == null) {
			rteValueBufferImplementationItemProvider = new RteValueBufferImplementationItemProvider(this);
		}

		return rteValueBufferImplementationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.ExternalEcuReceiver} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExternalEcuReceiverItemProvider externalEcuReceiverItemProvider;

	/**
	 * This creates an adapter for a {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.ExternalEcuReceiver}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExternalEcuReceiverAdapter() {
		if (externalEcuReceiverItemProvider == null) {
			externalEcuReceiverItemProvider = new ExternalEcuReceiverItemProvider(this);
		}

		return externalEcuReceiverItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.RteSendImplementation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RteSendImplementationItemProvider rteSendImplementationItemProvider;

	/**
	 * This creates an adapter for a {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.RteSendImplementation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRteSendImplementationAdapter() {
		if (rteSendImplementationItemProvider == null) {
			rteSendImplementationItemProvider = new RteSendImplementationItemProvider(this);
		}

		return rteSendImplementationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.IocSendImplementation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IocSendImplementationItemProvider iocSendImplementationItemProvider;

	/**
	 * This creates an adapter for a {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.IocSendImplementation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIocSendImplementationAdapter() {
		if (iocSendImplementationItemProvider == null) {
			iocSendImplementationItemProvider = new IocSendImplementationItemProvider(this);
		}

		return iocSendImplementationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.DirectComSendImplementation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DirectComSendImplementationItemProvider directComSendImplementationItemProvider;

	/**
	 * This creates an adapter for a {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.DirectComSendImplementation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDirectComSendImplementationAdapter() {
		if (directComSendImplementationItemProvider == null) {
			directComSendImplementationItemProvider = new DirectComSendImplementationItemProvider(this);
		}

		return directComSendImplementationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.TrustedFunctionComSendImplementation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TrustedFunctionComSendImplementationItemProvider trustedFunctionComSendImplementationItemProvider;

	/**
	 * This creates an adapter for a {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.TrustedFunctionComSendImplementation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTrustedFunctionComSendImplementationAdapter() {
		if (trustedFunctionComSendImplementationItemProvider == null) {
			trustedFunctionComSendImplementationItemProvider = new TrustedFunctionComSendImplementationItemProvider(this);
		}

		return trustedFunctionComSendImplementationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.PeriodicProxyComSendImplementation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PeriodicProxyComSendImplementationItemProvider periodicProxyComSendImplementationItemProvider;

	/**
	 * This creates an adapter for a {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.PeriodicProxyComSendImplementation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPeriodicProxyComSendImplementationAdapter() {
		if (periodicProxyComSendImplementationItemProvider == null) {
			periodicProxyComSendImplementationItemProvider = new PeriodicProxyComSendImplementationItemProvider(this);
		}

		return periodicProxyComSendImplementationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.ImmediateProxyComSendImplementation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ImmediateProxyComSendImplementationItemProvider immediateProxyComSendImplementationItemProvider;

	/**
	 * This creates an adapter for a {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.ImmediateProxyComSendImplementation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createImmediateProxyComSendImplementationAdapter() {
		if (immediateProxyComSendImplementationItemProvider == null) {
			immediateProxyComSendImplementationItemProvider = new ImmediateProxyComSendImplementationItemProvider(this);
		}

		return immediateProxyComSendImplementationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.TAckStatusVariableImplementation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TAckStatusVariableImplementationItemProvider tAckStatusVariableImplementationItemProvider;

	/**
	 * This creates an adapter for a {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.TAckStatusVariableImplementation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTAckStatusVariableImplementationAdapter() {
		if (tAckStatusVariableImplementationItemProvider == null) {
			tAckStatusVariableImplementationItemProvider = new TAckStatusVariableImplementationItemProvider(this);
		}

		return tAckStatusVariableImplementationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.FilterBufferImplementation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FilterBufferImplementationItemProvider filterBufferImplementationItemProvider;

	/**
	 * This creates an adapter for a {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.FilterBufferImplementation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFilterBufferImplementationAdapter() {
		if (filterBufferImplementationItemProvider == null) {
			filterBufferImplementationItemProvider = new FilterBufferImplementationItemProvider(this);
		}

		return filterBufferImplementationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.IocValueBufferImplementation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IocValueBufferImplementationItemProvider iocValueBufferImplementationItemProvider;

	/**
	 * This creates an adapter for a {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.IocValueBufferImplementation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIocValueBufferImplementationAdapter() {
		if (iocValueBufferImplementationItemProvider == null) {
			iocValueBufferImplementationItemProvider = new IocValueBufferImplementationItemProvider(this);
		}

		return iocValueBufferImplementationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.ComValueBufferImplementation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComValueBufferImplementationItemProvider comValueBufferImplementationItemProvider;

	/**
	 * This creates an adapter for a {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.ComValueBufferImplementation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createComValueBufferImplementationAdapter() {
		if (comValueBufferImplementationItemProvider == null) {
			comValueBufferImplementationItemProvider = new ComValueBufferImplementationItemProvider(this);
		}

		return comValueBufferImplementationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.InteractionRoot} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InteractionRootItemProvider interactionRootItemProvider;

	/**
	 * This creates an adapter for a {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.InteractionRoot}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInteractionRootAdapter() {
		if (interactionRootItemProvider == null) {
			interactionRootItemProvider = new InteractionRootItemProvider(this);
		}

		return interactionRootItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.TrustedFunctionRteSendImplementation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TrustedFunctionRteSendImplementationItemProvider trustedFunctionRteSendImplementationItemProvider;

	/**
	 * This creates an adapter for a {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.TrustedFunctionRteSendImplementation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTrustedFunctionRteSendImplementationAdapter() {
		if (trustedFunctionRteSendImplementationItemProvider == null) {
			trustedFunctionRteSendImplementationItemProvider = new TrustedFunctionRteSendImplementationItemProvider(this);
		}

		return trustedFunctionRteSendImplementationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.ComSendProxyInteraction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComSendProxyInteractionItemProvider comSendProxyInteractionItemProvider;

	/**
	 * This creates an adapter for a {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.ComSendProxyInteraction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createComSendProxyInteractionAdapter() {
		if (comSendProxyInteractionItemProvider == null) {
			comSendProxyInteractionItemProvider = new ComSendProxyInteractionItemProvider(this);
		}

		return comSendProxyInteractionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.PeriodicComSendProxy} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PeriodicComSendProxyItemProvider periodicComSendProxyItemProvider;

	/**
	 * This creates an adapter for a {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.PeriodicComSendProxy}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPeriodicComSendProxyAdapter() {
		if (periodicComSendProxyItemProvider == null) {
			periodicComSendProxyItemProvider = new PeriodicComSendProxyItemProvider(this);
		}

		return periodicComSendProxyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.ImmediateComSendProxy} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ImmediateComSendProxyItemProvider immediateComSendProxyItemProvider;

	/**
	 * This creates an adapter for a {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.ImmediateComSendProxy}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createImmediateComSendProxyAdapter() {
		if (immediateComSendProxyItemProvider == null) {
			immediateComSendProxyItemProvider = new ImmediateComSendProxyItemProvider(this);
		}

		return immediateComSendProxyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.ExecutionContext} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExecutionContextItemProvider executionContextItemProvider;

	/**
	 * This creates an adapter for a {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.ExecutionContext}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExecutionContextAdapter() {
		if (executionContextItemProvider == null) {
			executionContextItemProvider = new ExecutionContextItemProvider(this);
		}

		return executionContextItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.InfiniteloopImplementation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InfiniteloopImplementationItemProvider infiniteloopImplementationItemProvider;

	/**
	 * This creates an adapter for a {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.InfiniteloopImplementation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInfiniteloopImplementationAdapter() {
		if (infiniteloopImplementationItemProvider == null) {
			infiniteloopImplementationItemProvider = new InfiniteloopImplementationItemProvider(this);
		}

		return infiniteloopImplementationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.OneShootImplementation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OneShootImplementationItemProvider oneShootImplementationItemProvider;

	/**
	 * This creates an adapter for a {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.OneShootImplementation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOneShootImplementationAdapter() {
		if (oneShootImplementationItemProvider == null) {
			oneShootImplementationItemProvider = new OneShootImplementationItemProvider(this);
		}

		return oneShootImplementationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.EventPoolingImplementation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EventPoolingImplementationItemProvider eventPoolingImplementationItemProvider;

	/**
	 * This creates an adapter for a {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.EventPoolingImplementation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEventPoolingImplementationAdapter() {
		if (eventPoolingImplementationItemProvider == null) {
			eventPoolingImplementationItemProvider = new EventPoolingImplementationItemProvider(this);
		}

		return eventPoolingImplementationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.OsTaskActivateEntityStarter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OsTaskActivateEntityStarterItemProvider osTaskActivateEntityStarterItemProvider;

	/**
	 * This creates an adapter for a {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.OsTaskActivateEntityStarter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOsTaskActivateEntityStarterAdapter() {
		if (osTaskActivateEntityStarterItemProvider == null) {
			osTaskActivateEntityStarterItemProvider = new OsTaskActivateEntityStarterItemProvider(this);
		}

		return osTaskActivateEntityStarterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.OsEventSetEntityStarter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OsEventSetEntityStarterItemProvider osEventSetEntityStarterItemProvider;

	/**
	 * This creates an adapter for a {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.OsEventSetEntityStarter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOsEventSetEntityStarterAdapter() {
		if (osEventSetEntityStarterItemProvider == null) {
			osEventSetEntityStarterItemProvider = new OsEventSetEntityStarterItemProvider(this);
		}

		return osEventSetEntityStarterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.TimingTriggeringEntityStartCondition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TimingTriggeringEntityStartConditionItemProvider timingTriggeringEntityStartConditionItemProvider;

	/**
	 * This creates an adapter for a {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.TimingTriggeringEntityStartCondition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTimingTriggeringEntityStartConditionAdapter() {
		if (timingTriggeringEntityStartConditionItemProvider == null) {
			timingTriggeringEntityStartConditionItemProvider = new TimingTriggeringEntityStartConditionItemProvider(this);
		}

		return timingTriggeringEntityStartConditionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.RunnableEntityStartInteraction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RunnableEntityStartInteractionItemProvider runnableEntityStartInteractionItemProvider;

	/**
	 * This creates an adapter for a {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.RunnableEntityStartInteraction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRunnableEntityStartInteractionAdapter() {
		if (runnableEntityStartInteractionItemProvider == null) {
			runnableEntityStartInteractionItemProvider = new RunnableEntityStartInteractionItemProvider(this);
		}

		return runnableEntityStartInteractionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.BswSchedulableEntityStartInteraction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BswSchedulableEntityStartInteractionItemProvider bswSchedulableEntityStartInteractionItemProvider;

	/**
	 * This creates an adapter for a {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.BswSchedulableEntityStartInteraction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBswSchedulableEntityStartInteractionAdapter() {
		if (bswSchedulableEntityStartInteractionItemProvider == null) {
			bswSchedulableEntityStartInteractionItemProvider = new BswSchedulableEntityStartInteractionItemProvider(this);
		}

		return bswSchedulableEntityStartInteractionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.TimingTriggeringEntityStartImplementation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TimingTriggeringEntityStartImplementationItemProvider timingTriggeringEntityStartImplementationItemProvider;

	/**
	 * This creates an adapter for a {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.TimingTriggeringEntityStartImplementation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTimingTriggeringEntityStartImplementationAdapter() {
		if (timingTriggeringEntityStartImplementationItemProvider == null) {
			timingTriggeringEntityStartImplementationItemProvider = new TimingTriggeringEntityStartImplementationItemProvider(this);
		}

		return timingTriggeringEntityStartImplementationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.PlainEntityStartImplementation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PlainEntityStartImplementationItemProvider plainEntityStartImplementationItemProvider;

	/**
	 * This creates an adapter for a {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.PlainEntityStartImplementation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPlainEntityStartImplementationAdapter() {
		if (plainEntityStartImplementationItemProvider == null) {
			plainEntityStartImplementationItemProvider = new PlainEntityStartImplementationItemProvider(this);
		}

		return plainEntityStartImplementationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.StartOffsetCounterImplementation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StartOffsetCounterImplementationItemProvider startOffsetCounterImplementationItemProvider;

	/**
	 * This creates an adapter for a {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.StartOffsetCounterImplementation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStartOffsetCounterImplementationAdapter() {
		if (startOffsetCounterImplementationItemProvider == null) {
			startOffsetCounterImplementationItemProvider = new StartOffsetCounterImplementationItemProvider(this);
		}

		return startOffsetCounterImplementationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.CycleCounterImplementation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CycleCounterImplementationItemProvider cycleCounterImplementationItemProvider;

	/**
	 * This creates an adapter for a {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.CycleCounterImplementation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCycleCounterImplementationAdapter() {
		if (cycleCounterImplementationItemProvider == null) {
			cycleCounterImplementationItemProvider = new CycleCounterImplementationItemProvider(this);
		}

		return cycleCounterImplementationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.GeneratedEcuConfiguration} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GeneratedEcuConfigurationItemProvider generatedEcuConfigurationItemProvider;

	/**
	 * This creates an adapter for a {@link jp.ac.nagoya_u.is.nces.a_rte.model.rte.interaction.GeneratedEcuConfiguration}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGeneratedEcuConfigurationAdapter() {
		if (generatedEcuConfigurationItemProvider == null) {
			generatedEcuConfigurationItemProvider = new GeneratedEcuConfigurationItemProvider(this);
		}

		return generatedEcuConfigurationItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (interactionObjectItemProvider != null) interactionObjectItemProvider.dispose();
		if (interactionReferrableItemProvider != null) interactionReferrableItemProvider.dispose();
		if (internalEcuSenderItemProvider != null) internalEcuSenderItemProvider.dispose();
		if (externalEcuSenderItemProvider != null) externalEcuSenderItemProvider.dispose();
		if (sendInteractionItemProvider != null) sendInteractionItemProvider.dispose();
		if (receiveInteractionItemProvider != null) receiveInteractionItemProvider.dispose();
		if (receiverItemProvider != null) receiverItemProvider.dispose();
		if (internalEcuReceiverItemProvider != null) internalEcuReceiverItemProvider.dispose();
		if (rteValueBufferImplementationItemProvider != null) rteValueBufferImplementationItemProvider.dispose();
		if (externalEcuReceiverItemProvider != null) externalEcuReceiverItemProvider.dispose();
		if (rteSendImplementationItemProvider != null) rteSendImplementationItemProvider.dispose();
		if (iocSendImplementationItemProvider != null) iocSendImplementationItemProvider.dispose();
		if (directComSendImplementationItemProvider != null) directComSendImplementationItemProvider.dispose();
		if (trustedFunctionComSendImplementationItemProvider != null) trustedFunctionComSendImplementationItemProvider.dispose();
		if (periodicProxyComSendImplementationItemProvider != null) periodicProxyComSendImplementationItemProvider.dispose();
		if (immediateProxyComSendImplementationItemProvider != null) immediateProxyComSendImplementationItemProvider.dispose();
		if (tAckStatusVariableImplementationItemProvider != null) tAckStatusVariableImplementationItemProvider.dispose();
		if (filterBufferImplementationItemProvider != null) filterBufferImplementationItemProvider.dispose();
		if (iocValueBufferImplementationItemProvider != null) iocValueBufferImplementationItemProvider.dispose();
		if (comValueBufferImplementationItemProvider != null) comValueBufferImplementationItemProvider.dispose();
		if (interactionRootItemProvider != null) interactionRootItemProvider.dispose();
		if (trustedFunctionRteSendImplementationItemProvider != null) trustedFunctionRteSendImplementationItemProvider.dispose();
		if (comSendProxyInteractionItemProvider != null) comSendProxyInteractionItemProvider.dispose();
		if (periodicComSendProxyItemProvider != null) periodicComSendProxyItemProvider.dispose();
		if (immediateComSendProxyItemProvider != null) immediateComSendProxyItemProvider.dispose();
		if (executionContextItemProvider != null) executionContextItemProvider.dispose();
		if (infiniteloopImplementationItemProvider != null) infiniteloopImplementationItemProvider.dispose();
		if (oneShootImplementationItemProvider != null) oneShootImplementationItemProvider.dispose();
		if (eventPoolingImplementationItemProvider != null) eventPoolingImplementationItemProvider.dispose();
		if (osTaskActivateEntityStarterItemProvider != null) osTaskActivateEntityStarterItemProvider.dispose();
		if (osEventSetEntityStarterItemProvider != null) osEventSetEntityStarterItemProvider.dispose();
		if (timingTriggeringEntityStartConditionItemProvider != null) timingTriggeringEntityStartConditionItemProvider.dispose();
		if (runnableEntityStartInteractionItemProvider != null) runnableEntityStartInteractionItemProvider.dispose();
		if (bswSchedulableEntityStartInteractionItemProvider != null) bswSchedulableEntityStartInteractionItemProvider.dispose();
		if (timingTriggeringEntityStartImplementationItemProvider != null) timingTriggeringEntityStartImplementationItemProvider.dispose();
		if (plainEntityStartImplementationItemProvider != null) plainEntityStartImplementationItemProvider.dispose();
		if (startOffsetCounterImplementationItemProvider != null) startOffsetCounterImplementationItemProvider.dispose();
		if (cycleCounterImplementationItemProvider != null) cycleCounterImplementationItemProvider.dispose();
		if (generatedEcuConfigurationItemProvider != null) generatedEcuConfigurationItemProvider.dispose();
	}

}
